name: Download Datasets

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install python requests
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run download script
        run: |
          python scripts/download_datasets.py
